version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: tasmota-rabbitmq
    ports:
      - "5672:5672"      # AMQP port for local CLI access
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      tasmota_net:
        ipv4_address: 172.25.0.10
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Device containers will be added by the create-devices command
  # or can be included from docker-compose.override.yml

networks:
  tasmota_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  rabbitmq_data: 